"""initial migration

Revision ID: 2181bca5d676
Revises: 
Create Date: 2024-02-08 17:13:43.452308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2181bca5d676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_token',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('motion_size',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('size_id'),
    sa.UniqueConstraint('size_name')
    )
    op.create_table('object_type',
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('object_type_id')
    )
    op.create_table('position',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('google_drive_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notification_preference', sa.String(length=10), nullable=False),
    sa.Column('motion_detection_mode', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('google_drive_token',
    sa.Column('google_drive_token_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('google_drive_token_id')
    )
    op.create_table('motion_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.position_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['motion_size.size_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('detected_object',
    sa.Column('detected_object_id', sa.Integer(), nullable=False),
    sa.Column('motion_event_id', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motion_event_id'], ['motion_event.event_id'], ),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_type.object_type_id'], ),
    sa.PrimaryKeyConstraint('detected_object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_object')
    op.drop_table('roles_users')
    op.drop_table('motion_event')
    op.drop_table('google_drive_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('position')
    op.drop_table('object_type')
    op.drop_table('motion_size')
    op.drop_table('gmail_token')
    # ### end Alembic commands ###
